### PR TITLE
Add unit tests for Jenkiexs.Jobs.get_console_text/2

### LINKED ISSUE #10: [Unit Tests] Make unit test for Jenkiexs.Jobs.get_console_text/2

### PR DESCRIPTION
**Pull request by denvera**
This is to resolve #10. Please let me know if you'd like anything added/changed!

### CODE REVIEW

**Comment by GPrimola** [comment]
Hey @denvera thanks for this! Are you playing at Hacktoberfest?

**Comment by denvera** [comment]
Hi @GPrimola, yes I am!

**Comment by GPrimola** [comment]
Great @denvera, I'll be labeling this as a Hacktoberfest repository and issue solved!

Thank you very much for you contribution! :)

**Comment by denvera** [comment]
Thanks so much @GPrimola - would you mind adding the `hacktoberfest-accepted` label to this PR if possible?

**Pull request merged**
